### ISSUE TITLE
Release Results Week 1

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#97]
- [Results Question 1 page](https://www.synapse.org/#!Synapse:syn21849255/wiki/603188)
- Release date: May 28, 2020

**Comment by thomasyu888** [comment]
Done @tschaffter, how do you think it looks?

**Comment by tschaffter** [comment]
@thomasyu888 Here are a few notes:

- Rename the column `ranking` to `Rank` (shorter)
- Set the `Rank` column as the first column

Release of Docker images: ultimately we may want to provide an archived version of the image to make sure that they are available publicly. For now it's OK to leave as it is and rely on the participants making them public. I'll also add more messages on some pages to make it clear to participants that we may enforce the release of archived version publicly in future results release.

**Comment by thomasyu888** [comment]
Im going to push back a bit on the archiving of Docker images because we had discussed this at some point and we converged on having participants making them public.   Perhaps this should ultimately something the platform should provide.  

I'm not a huge fan of creating duplicates of every single docker image...  I did open an issue #111
